server:
  port: 8080
  servlet:
    context-path: /api
spring:
  mvc:
    pathmatch:
      # Spring默认的路径匹配策略为PATH_PATTERN_PARSER，而SpringFox假设为ANT_PATH_MATCHER
      matching-strategy: ant_path_matcher

# swagger 配置
springfox:
  documentation:
    # 是否启用Swagger扫描代码生成文档
    enabled: true
    open-api:
      # 是否启用Swagger的open-api
      enabled: false
    swagger-ui:
      # 是否启用Swagger的Web UI
      enabled: true
      # 配置文档基础路径，此时路径为：/doc/swagger-ui/index.html
      base-url: /doc